---
title: "TRESH_RQ2_Figures"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    theme: spacelab
fontsize: 16pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Packages
```{r Load Packages, message=TRUE, warning=TRUE}
# load packages
install.packages("pacman", repos = "http://cran.us.r-project.org")
library(pacman)
p_load(tidyverse, ggridges, ggplot2, patchwork, rstatix, reshape2, ggdist)

options(scipen=30000)
```

# Load Data
```{r Load Data, echo=TRUE}
# load in datafiles

df_long_suittask <- read.csv("Dataframes/df_long_suittask.csv", header=TRUE)
# remove added x column
df_long_suittask <- df_long_suittask[-1]

df_long_suitage <- read.csv("Dataframes/df_long_suitage.csv", header=TRUE)
df_long_suitage_sum <- read.csv("Dataframes/df_long_suitage_sum.csv", header=TRUE)
posthoc_age_df <- read.csv("Dataframes/posthoc_age_df.csv", header=TRUE)
# remove added x column
df_long_suitage <- df_long_suitage[-1]
df_long_suitage_sum <- df_long_suitage_sum[-1]

df_long_suitgroup <- read.csv("Dataframes/df_long_suitgroup.csv", header=TRUE)
df_long_suitgroup_sum <- read.csv("Dataframes/df_long_suitgroup_sum.csv", header=TRUE)
posthoc_group_df <- read.csv("Dataframes/posthoc_group_df.csv", header=TRUE)
# remove added x column
df_long_suitgroup <- df_long_suitgroup[-1]
df_long_suitgroup_sum <- df_long_suitgroup_sum[-1]

df_long_suitrole <- read.csv("Dataframes/df_long_suitrole.csv", header=TRUE)
df_long_suitrole_sum <- read.csv("Dataframes/df_long_suitrole_sum.csv", header=TRUE)
posthoc_role_df <- read.csv("Dataframes/posthoc_role_df.csv", header=TRUE)
# remove added x column
df_long_suitrole <- df_long_suitrole[-1]
df_long_suitrole_sum <- df_long_suitrole_sum[-1]
```

# Variable transformation
```{r}
# Bring variables into right format

# factors
df_long_suittask <- df_long_suittask %>%
  mutate(across(c(ParticipantID, robot, robot_type, starts_with("rank"),starts_with("suit")), as.factor))

df_long_suitage <- df_long_suitage %>%
  mutate(across(c(ParticipantID, robot, robot_type, starts_with("rank"),starts_with("suit")), as.factor))

df_long_suitgroup <- df_long_suitgroup %>%
  mutate(across(c(ParticipantID, robot, robot_type, starts_with("rank"),starts_with("suit")), as.factor))

df_long_suitrole <- df_long_suitrole %>%
  mutate(across(c(ParticipantID, robot, robot_type, starts_with("rank"),starts_with("suit")), as.factor))
```

# Figures
```{r}
# set theme
theme_set(theme_light()  + theme(
    axis.title.x = element_text(size=rel(1.2), color = "black", face = "bold"), 
    axis.title.y = element_text(size = rel(1.2), color = "black", face = "bold"), 
    axis.text.x = element_text(size=rel(1), color = "black"),
    axis.text.y = element_text(size = rel(1), color = "black"), 
    plot.title = element_text(size = rel(1.2), face = "bold"), 
    legend.title = element_text(size = rel(1.2), face = "bold"), 
    legend.text = element_text(size = rel(1)),
    strip.text = element_text(color="black")
  ))

colors_suittask <-  c(
  "#ff90b3", 
  "#ff99c8",
  "#fb6f92",
  "#ff8fab",
 alpha("#ff90b3",0.5),
 alpha("#ff99c8",0.5),
 alpha("#fb6f92",0.5),
 alpha("#ff8fab",0.5)
)

labels_plot_suitability = c(
      suitgroups = "Groups*", 
      suitindivgroupneither = "Neither*", 
      suitindividual = "Individuals*", 
      suitadults = "Adults*", 
      suitageneither = "Neither*", 
      suitchildren = "Children*", 
      suitnovice = "Novice*", 
      suitpeer = "Peer*", 
      suitteacher = "Teacher*", 
      suittutor = "Tutor*", 
      spacer1 ="",
      spacer2="",
      spacer3="")

plot_colors_suitability <- c(
  "#5f9ea0",  # suitgroups
  "#b0e0e6",  # suitindividual
  "#99AFC2", # suitindivgroupneither
  "#90a955",  # suitadults
   "#a7c957",    # suitchildren,
  "#a5be00", #suitageneither
  "#f9c74f",  # suitnovice
  "#daa520",  # suitpeer,
  "#ffd819", #suitteacher,
  "#eeba0b",#suittutor
  alpha("#5f9ea0",0.5),  # suitgroups
  alpha("#b0e0e6", 0.5), # suitindividual
 alpha("#99AFC2",0.5), # suitindivgroupneither
  alpha("#90a955", 0.5), # suitadults
   alpha("#a7c957",0.5),    # suitchildren,
  alpha("#a5be00",0.5), #suitageneither
  alpha("#f9c74f",0.5),  # suitnovice
  alpha("#daa520",0.5),  # suitpeer,
  alpha("#ffd819",0.5), #suitteacher,
  alpha("#eeba0b",0.5))#suittutor
```

## Task suitability
### Ridge plot
```{r message=FALSE, warning=FALSE}
suittask_means_robottype_plot <- ggplot(df_long_suittask, aes(x = value, y = suittask, fill = robot_type)) + 
 geom_density_ridges(aes(color = robot_type), scale = 0.6, alpha = 0.7, rel_min_height = 0.05) +
  stat_pointinterval(position = position_dodge(.5, preserve = "single"), aes(color=robot_type, fill=robot_type), scale=0.6, alpha=0.7) +
 annotate("text", x = 100, y = c("suitmath","suitart"), label = "*", size=rel(7)) +
  labs(y = "Task", x = "Rating") +  
  scale_fill_manual(values = c("#577590","#99AFC2"), labels=c("Hard","Soft")) + 
  scale_color_manual(values = c("#577590","#99AFC2")) +  
 scale_x_continuous(breaks=c(0,20,40,60,80,100), limits = c(0,100)) +  
 scale_y_discrete(
   labels = c("Creating art","Helping feel better","Learning maths","Listening read"), guide = guide_axis(angle = 45)) + 
  guides(fill =FALSE, color = FALSE) + theme(legend.position="top", axis.text.x = element_text(size=rel(1.3)), axis.text.y = element_text(size=rel(1.3))) + coord_flip()

suittask_means_robottype_plot

ggsave("Figures/tasksuitability_ridge.png",suittask_means_robottype_plot, width = 10, height = 5, dpi = 800)
```

### Spider plot
```{r message=FALSE, warning=FALSE}
# calculate SE for plot
df_long_suittask$value_num <- as.numeric(as.character(df_long_suittask$value))

df_long_suittask_sum <- df_long_suittask %>%
  group_by(robot_type, suittask) %>%
  na.omit(df_long_suittask$value_num) %>%
  dplyr::summarise( 
    n=n(),
    mean=mean(value_num),
    sd=sd(value_num)
  ) %>%
  mutate( se=sd/sqrt(n))

# add interaction column
df_long_suittask_sum$interact <- interaction(df_long_suittask_sum$suittask, df_long_suittask_sum$robot_type)

spiderplot_tasks <- ggplot(df_long_suittask_sum) +
  geom_hline(
    data = data.frame(y = c(0, 25, 50)),  # Inner grid lines only
    aes(yintercept = y), 
    color = "lightgrey", na.rm = TRUE
  ) + 
  geom_col(
    aes(
      x = fct_relevel(suittask,"suitart","suitmath","suitdifftask","suitread"),
      y = mean,
      color = interact, 
      fill = interact,
    ),
    position = "dodge2",
    show.legend = TRUE,
    na.rm = TRUE
  ) +
  geom_segment(aes(
      x = fct_relevel(suittask,"suitart","suitmath","suitdifftask","suitread"),
      y = 0,
      xend = fct_relevel(suittask,"suitart","suitmath","suitdifftask","suitread"),
      yend = 78,
    ),
    linetype = "dashed",
    color = "gray12",
  ) + 
 coord_radial(rotate_angle = FALSE, expand = FALSE) +
  scale_y_continuous(
    limits = c(-10, 85),  # Set limit just below the outermost circle
    expand = c(0, 0),    
    breaks = c(0, 25, 50)  # Inner grid lines
  ) +
  geom_errorbar(aes(x=suittask,ymin = mean - se, ymax = mean + se, group=robot_type), position = position_dodge(width = 0.9), width = 0.2
                )+
    annotate(x = 0.5, y = 28, 
    label = "25", 
    geom = "text", 
    color = "gray12",
    size=rel(5),
    hjust=0.5,
    vjust = 0  # Align the label at the bottom of the text box
  ) +
  annotate(
    x = 0.5, 
    y = 53, 
    label = "50", 
    geom = "text", 
    color = "gray12",
    size=rel(5),
    hjust = 0.5,
    vjust = 0  # Align the label at the bottom of the text box
  ) +
  theme(
     axis.text.y = element_blank(),
    axis.text.x = element_text(size = rel(1.9)),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),  # Remove default grid lines
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.x = element_blank(), 
    axis.title.y = element_blank(),
    panel.border = element_blank(),
    strip.background = element_rect(color = "black"),
 plot.background = element_rect(fill = "white", color = NA)
  ) +
    scale_color_manual(values = colors_suittask) +
  scale_fill_manual(values = colors_suittask,na.translate = FALSE) +
  scale_x_discrete(expand = c(0,0),labels = c("Creating art*","Learning math*","Feeling better","Listening read",""),na.translate = FALSE)+
  guides(color = FALSE, fill=FALSE)

spiderplot_tasks

ggsave("Figures/tasksuitability_spider.png", spiderplot_tasks, width = 10, height = 9, dpi = 800)
```
## Age
```{r}
posthoc_age_plot <- posthoc_age_df %>%
  ggplot(aes(x=suit_age, y=emmean, color=factor(robot_type))) +
  geom_point( size = 2) +
  # Add error bars (emmean ± SE)
  geom_errorbar(aes(ymin = emmean - SE, ymax = emmean + SE), 
                width = 0.2,  # width of the error bars
                size = 0.5) + 
  # Rotate x-axis labels by 45 degrees
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  # Add appropriate axis labels
  labs(x = "Age", y = "Estimated Marginal Mean", color="Robot Type") + scale_color_manual(
    values = c("#577590","#809BB3"),  # Example of changing legend colors
    labels = c("1" = "Hard", "2" = "Soft")  # Example of custom labels
  ) + scale_x_discrete(labels=c("Adults","Neither","Children"))

posthoc_age_plot

ggsave("Figures/posthoc_age_suppl.png",posthoc_age_plot, dpi=800, width=10,height=6 )
```

## Context
```{r}
posthoc_group_plot <- posthoc_group_df %>%
  ggplot(aes(x=suit_group, y=emmean, color=factor(robot_type))) +
  geom_point( size = 2) +
  # Add error bars (emmean ± SE)
  geom_errorbar(aes(ymin = emmean - SE, ymax = emmean + SE), 
                width = 0.2,  # width of the error bars
                size = 0.5) + 
  # Rotate x-axis labels by 45 degrees
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  # Add appropriate axis labels
  labs(x = "Context", y = "Estimated Marginal Mean", color="Robot Type") + scale_color_manual(
    values = c("#577590","#809BB3"),  # Example of changing legend colors
    labels = c("1" = "Hard", "2" = "Soft")  # Example of custom labels
  ) + scale_x_discrete(labels=c("Groups","Neither","Individuals"))

posthoc_group_plot

ggsave("Figures/posthoc_group_suppl.png",posthoc_group_plot, dpi=800, width=10,height=6 )
```

## Role
```{r}
posthoc_role_plot <- posthoc_role_df %>%
  ggplot(aes(x=suit_role, y=emmean, color=factor(robot_type))) +
  geom_point( size = 2) +
  # Add error bars (emmean ± SE)
  geom_errorbar(aes(ymin = emmean - SE, ymax = emmean + SE), 
                width = 0.2,  # width of the error bars
                size = 0.5) + 
  # Rotate x-axis labels by 45 degrees
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  # Add appropriate axis labels
  labs(x = "Role", y = "Estimated Marginal Mean", color="Robot Type") + scale_color_manual(
    values = c("#577590","#809BB3"),  # Example of changing legend colors
    labels = c("1" = "Hard", "2" = "Soft")  # Example of custom labels
  ) + scale_x_discrete(labels=c("Novice","Peer","Teacher","Tutor"))

posthoc_role_plot

ggsave("Figures/posthoc_role_suppl.png",posthoc_role_plot, dpi=800, width=10,height=6 )
```

## Combined
```{r message=FALSE, warning=FALSE}
# create joined df

# rename columns to merge dfs
names(df_long_suitgroup_sum)[names(df_long_suitgroup_sum) == "suitgroup"] <- "suitability"
names(df_long_suitage_sum)[names(df_long_suitage_sum) == "suitage"] <- "suitability"
names(df_long_suitrole_sum)[names(df_long_suitrole_sum) == "suitrole"] <- "suitability"

# merge
merged_df_suitability <- rbind(df_long_suitgroup_sum, df_long_suitage_sum,df_long_suitrole_sum)

# create interaction term, labels & colors
merged_df_suitability$interact <- interaction(merged_df_suitability$suitability, merged_df_suitability$robot_type)

# add spacer to create gaps between groups
df_spacer_suitability <- data.frame(suitability = c("spacer1", "spacer2","spacer3"),
                        robot_type = c(NA,NA,NA),  # NA or some value if needed
                        mean = c(NA,NA,NA),
                        n = c(NA,NA,NA),
                        sd = c(NA,NA,NA),
                        se = c(NA,NA,NA),
                        interact = c(NA,NA,NA)
                    
                        ) # NA or 0 or some value if needed

# Combine the original dataframe with the spacer row
plot_df_suitability <- rbind(merged_df_suitability, df_spacer_suitability)
df_no_spacers_suitability <- plot_df_suitability %>%
  filter(!suitability %in% c("spacer1", "spacer2", "spacer3"))

# plot
spiderplot_suitability <- ggplot(plot_df_suitability) +
  # Custom grid lines using geom_hline
  geom_hline(
    aes(yintercept = y), 
    data = data.frame(y = c(0, 0.25, 0.50)),  # Inner grid lines only
    color = "lightgrey", na.rm = TRUE
  ) + 
  geom_col(
    aes(
      x = fct_relevel(suitability,"suitteacher","suittutor","suitpeer","suitnovice","spacer3","suitageneither","suitadults","suitchildren","spacer1","suitindivgroupneither","suitgroups","suitindividual","spacer2"),
      y = mean,
      color = as.factor(interact), 
      fill = as.factor(interact)
    ),
    position = "dodge2",
    show.legend = TRUE,
    na.rm = TRUE
  ) +
  geom_segment(data=df_no_spacers_suitability,
    aes(
      x = fct_relevel(suitability,"suitteacher","suittutor","suitpeer","suitnovice","spacer3","suitageneither","suitadults","suitchildren","spacer1","suitindivgroupneither","suitgroups","suitindividual","spacer2"),
      y = 0,
      xend = fct_relevel(suitability,"suitteacher","suittutor","suitpeer","suitnovice","spacer3","suitageneither","suitadults","suitchildren","spacer1","suitindivgroupneither","suitgroups","suitindividual","spacer2"),
      yend = 0.78,
    ),
    linetype = "dashed",
    color = "gray12",
  ) + 
 coord_radial(rotate_angle = FALSE, expand = FALSE) +
  scale_y_continuous(
    limits = c(-0.1, 0.85),  # Set limit just below the outermost circle
    expand = c(0, 0),    
    breaks = c(0, 0.25, 0.50)  # Inner grid lines
  ) +
  geom_errorbar(data=merged_df_suitability, aes(x=suitability,ymin = mean - se, ymax = mean + se, group=robot_type), position = position_dodge(width = 0.9), width = 0.2)+
  annotate(
    x = 0, y = 0.28, 
    label = "0.25", 
    geom = "text", 
    color = "gray12",
    size=rel(5),
    hjust = 0.5,  # Center the label horizontally
    vjust = 0  # Align the label at the bottom of the text box
  ) +
  annotate(
    x = 0, 
    y = 0.53, 
    label = "0.50", 
    geom = "text", 
    color = "gray12",
    size=rel(5),
    hjust = 0.5,  # Center the label horizontally
    vjust = 0  # Align the label at the bottom of the text box
  ) +
    annotate(
    x = 12.7, 
    y = 0.13, 
    label = "Context", 
    geom = "text", 
    color = "black",
    fontface="bold",
    size=rel(4.5),
    vjust = 0,
    angle=-70# Align the label at the bottom of the text box
  ) +
      annotate(
    x = 8.83, 
    y = 0.07, 
    label = "Age", 
    geom = "text", 
    color = "black",
    fontface="bold",
    size=rel(4.5),
    vjust = 0,
    angle=33# Align the label at the bottom of the text box
  ) +
      annotate(
    x = 4.82, 
    y = 0.08, 
    label = "Role", 
    geom = "text", 
    color = "black",
    fontface="bold",
    size=rel(4.5),
    vjust = 0,
    angle=-225# Align the label at the bottom of the text box
  ) +
  theme(
     axis.text.y = element_blank(),
    axis.text.x = element_text(size = rel(1.9)),
    panel.grid.major = element_blank(),  # Remove default grid lines
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.x = element_blank(), 
    axis.title.y = element_blank(),
    strip.background = element_rect(color = "black"),
    panel.border = element_blank(),
 legend.position = "top"
  ) + 
  scale_fill_manual(values = plot_colors_suitability,na.translate = FALSE) +
    scale_color_manual(values = plot_colors_suitability) +
  scale_x_discrete(expand = c(0,0),labels = labels_plot_suitability,na.translate = FALSE)+
  guides(color = FALSE, fill=FALSE)

spiderplot_suitability
```


## Publication figure
```{r message=FALSE, warning=FALSE}
combined_suitability <- spiderplot_tasks | spiderplot_suitability

ggsave("Figures/spiderplot_suitability_combined.png", combined_suitability, width = 15, height = 8, dpi = 800)
```

