---
title: "TRESH_RQ1_Figures"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    theme: spacelab
fontsize: 16pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages
```{r Load Packages, message=FALSE, warning=FALSE}
# load packages
install.packages("pacman", repos = "http://cran.us.r-project.org")
library(pacman)
p_load(tidyverse, ggridges, ggplot2, patchwork, rstatix, reshape2, ggdist)
```

## Load Data
```{r Load Data, echo=TRUE}
# load in datafiles

df_survey <- read.csv("dataframes/softbots_study1.csv", header=TRUE)
# remove added x column
df_survey <- df_survey[-1]

df_unique <- read.csv("dataframes/df_unique.csv", header=TRUE)
# remove added x column
df_unique <- df_unique[-1]
```

## Variable transformation
```{r}
# Bring variables into right format

# factors
df_survey <- df_survey %>%
  mutate(across(c(ParticipantID, consent, gender, country, teach.school, robot, robot_type, starts_with("rank"),starts_with("suit"),starts_with("favorite"), attentioncheck1, attentioncheck2, source, videos.amount, movies.amount, robots.skepticism), as.factor))

# numeric
df_survey <- df_survey %>%
  mutate(across(c(starts_with("prior"), teach.age_1, teach.age_2,teach.age_3,teach.age_4,teach.age_5,teach.age_6,teach.subject_1,teach.subject_2,teach.subject_3,teach.subject_4,teach.subject_5,teach.subject_6,teach.subject_7,teach.subject_8,teach.subject_9,teach.subject_10, Views, Viewssuit, totalviews),as.numeric
  ))
```

```{r}
# hard coded as 1, soft as 2

# reshape to long
df_long_dimensions <- tidyr::pivot_longer(df_survey, cols = c("familiarrobot","familiarobjec","safety","competence","comfortable","friendliness","creepycute","badgood","physicalwarm","socialwarm","humanform","humanmotion","socialcompetence","socialness","socialintelligence","intelligence"), names_to = "dimension", values_to = "value")
```

# Figures
```{r}
# set theme
theme_set(theme_light()  + theme(
    axis.title.x = element_text(size=rel(1.2), color = "black", face = "bold"), 
    axis.title.y = element_text(size = rel(1.2), color = "black", face = "bold"), 
    axis.text.x = element_text(size=rel(1), color = "black"),
    axis.text.y = element_text(size = rel(1), color = "black"), 
    plot.title = element_text(size = rel(1.2), face = "bold"), 
    legend.title = element_text(size = rel(1.2), face = "bold"), 
    legend.text = element_text(size = rel(1)),
    strip.text = element_text(color="black")
  ))

labels_plot = c(
      badgood = "Bad/Good", 
      comfortable = "Comfortable", 
      competence = "Competence*", 
      creepycute = "Creepy/Cute", 
      familiarobjec = "Familiarity Object", 
      familiarrobot = "Familiarity Robot*", 
      friendliness = "Friendliness", 
      humanform = "Human-like form*", 
      humanmotion = "Human-like motion", 
      intelligence = "Intelligence*", 
      physicalwarm = "Physical warmth*", 
      safety = "Safety", 
      socialcompetence = "Social competence", 
      socialintelligence = "Social intelligence", 
      socialness = "Socialness", 
      socialwarm = "Social warmth")

labels_plot2 = c(
      badgood = "Good", 
      comfortable = "Comfortable", 
      competence = "Competent*", 
      creepycute = "Cute", 
      familiarobjec = "Familiar with object", 
      familiarrobot = "Familiar with robot*", 
      friendliness = "Friendly", 
      humanform = "Human-like form*", 
      humanmotion = "Human-like motion", 
      intelligence = "Intelligent*", 
      physicalwarm = "Physically warm*", 
      safety = "Safe", 
      socialcompetence = "Socially competent", 
      socialintelligence = "Socially intelligent", 
      socialness = "Social", 
      socialwarm = "Socially warm",
      spacer1 ="",
      spacer2="",
      spacer3="",
      spacer4="",
      spacer5="",
      spacer6="")

plot_colors <- c("#ffa06d",  # Good
  "#ffa07a",  # Comfortable
  "#5f9ea0",  # Competent
 "#ea8c55",# Cute
  "#ff6f61",  # Familiar Object
   "#FF9389",    # Familiar Robot
  "#ff8c49",  # Friendly
  "#ffdb58",  # Human Form
  "#daa520",  # Human Motion
  "#ff69b4",  # Intelligent
  "#8a9a5b",# Physical Warm   
  "#D7885B",# Safe
  "#b0e0e6",  # Socially Competent
  "#e27396",  # Social Intelligent
  "#ffad86",  # Social
  "#b2b260",
 alpha("#ffa06d",0.5),  # Good
 alpha("#ffa07a",0.5),   # Comfortable
 alpha("#5f9ea0",0.5),  # Competent
 alpha("#ea8c55",0.5), # Cute
 alpha("#ff6f61",0.5),   # Familiar Object
 alpha("#FF9389",0.5),  # Familiar Robot
 alpha("#ff8c49",0.5),   # Friendly
 alpha("#ffdb58",0.5),   # Human Form
 alpha("#daa520",0.5), # Human Motion
 alpha("#ff69b4",0.5),  # Intelligent
 alpha("#8a9a5b",0.5),   # Physical Warm
 alpha("#D7885B",0.5), # Safe
 alpha("#b0e0e6",0.5),   # Socially Competent
 alpha("#e27396",0.5),   # Social Intelligent
 alpha("#ffad86",0.5),   # Social
 alpha("#b2b260",0.5))
```

## Spider plot by robot type
```{r warning=FALSE}
# create df with means
plot_df <- df_long_dimensions %>%
  group_by(dimension, robot_type) %>%
  dplyr::summarise(
mean_rating = mean(as.numeric(value), na.rm=TRUE)
  )


#add interaction column
plot_df$interact <- interaction(plot_df$dimension, plot_df$robot_type)

# add spacer to create gaps between dimensions
df_spacer <- data.frame(dimension = c("spacer1", "spacer2","spacer3","spacer4","spacer5","spacer6"),
                        robot_type = c(NA,NA,NA,NA,NA,NA),  # NA or some value if needed
                        mean_rating = c(NA,NA,NA,NA,NA,NA)) # NA or 0 or some value if needed

# Combine the original dataframe with the spacer row
plot_df <- rbind(plot_df, df_spacer)

df_no_spacers <- plot_df %>%
  filter(!dimension %in% c("spacer1", "spacer2", "spacer3", "spacer4", "spacer5","spacer6"))

# calculate error bars
df_long_dimensions_sum<- df_long_dimensions %>%
  group_by(dimension, robot_type) %>%
  dplyr::summarise( 
    n=n(),
    mean=mean(as.numeric(value), na.rm=TRUE),
    sd=sd(as.numeric(value), na.rm=TRUE)
  ) %>%
  mutate(se=sd/sqrt(n))

spiderplot <- ggplot(plot_df) +
  # Custom grid lines using geom_hline
  geom_hline(
    aes(yintercept = y), 
    data = data.frame(y = c(0, 25, 50)),  # Inner grid lines only
    color = "lightgrey", na.rm = TRUE
  ) + 
  geom_col(
    aes(
      x = fct_relevel(dimension,"socialness","friendliness","comfortable","creepycute","badgood","safety","spacer3","familiarrobot","familiarobjec","spacer1","intelligence","socialintelligence","spacer6","humanmotion","humanform","spacer2","competence","socialcompetence","spacer5","physicalwarm","socialwarm","spacer4"),
      y = mean_rating,
      color = as.factor(interact), 
      fill = as.factor(interact)
    ),
    position = "dodge2",
    show.legend = TRUE,
    na.rm = TRUE
  ) +
  geom_segment(data=df_no_spacers,
    aes(
      x = fct_relevel(dimension,"socialness","friendliness","comfortable","creepycute","badgood","safety","spacer3","familiarrobot","familiarobjec","spacer1","intelligence","socialintelligence","spacer6","humanmotion","humanform","spacer2","competence","socialcompetence","spacer5","physicalwarm","socialwarm","spacer4"),
      y = 0,
      xend = fct_relevel(dimension,"socialness","friendliness","comfortable","creepycute","badgood","safety","spacer3","familiarrobot","familiarobjec","spacer1","intelligence","socialintelligence","spacer6","humanmotion","humanform","spacer2","competence","socialcompetence","spacer5","physicalwarm","socialwarm","spacer4"),
      yend = 60,
    ),
    linetype = "dashed",
    color = "gray12",
  ) + 
 coord_radial(rotate_angle = FALSE, expand = FALSE) +
  scale_y_continuous(
    limits = c(-10, 65),  # Set limit just below the outermost circle
    expand = c(0, 0),    
    breaks = c(0, 25, 50)  # Inner grid lines
  ) +
  geom_errorbar(data=df_long_dimensions_sum, aes(x=dimension,ymin = mean - se, ymax = mean + se, group=robot_type), position = position_dodge(width = 0.9), width = 0.2)+
  annotate(
    x = 0, y = 28, 
    label = "25", 
    geom = "text", 
    color = "gray12",
    size=rel(4),
    hjust = 0.5,  # Center the label horizontally
    vjust = 0  # Align the label at the bottom of the text box
  ) +
  annotate(
    x = 0, 
    y = 53, 
    label = "50", 
    geom = "text", 
    color = "gray12",
    size=rel(4),
    hjust = 0.5,  # Center the label horizontally
    vjust = 0  # Align the label at the bottom of the text box
  ) +
  annotate(
    x =21.9, 
    y = 8, 
    label = "Warmth", 
    geom = "text", 
    color = "black",
    fontface="bold",
    size=rel(5),
    vjust = 0,
    angle=-82# Align the label at the bottom of the text box
  ) +
    annotate(
    x = 6.75, 
    y = 6.5, 
    label = "Traits", 
    geom = "text", 
    color = "black",
    fontface="bold",
    size=rel(4),
    vjust = 0,
    angle=160# Align the label at the bottom of the text box
  ) +
    annotate(
    x = 9.85, 
    y = 11, 
    label = "Familiarity", 
    geom = "text", 
    color = "black",
    fontface="bold",
    size=rel(4),
    vjust = 0,
    angle=109# Align the label at the bottom of the text box
  ) +
    annotate(
    x = 12.8, 
    y = 12, 
    label = "Intelligence", 
    geom = "text", 
    color = "black",
    fontface="bold",
    size=rel(4),
    vjust = 0,
    angle=62# Align the label at the bottom of the text box
  ) +
    annotate(
    x = 15.87, 
    y = 15.7, 
    label = "Human-likeness", 
    geom = "text", 
    color = "black",
    fontface="bold",
    size=rel(4),
    vjust = 0,
    angle=13# Align the label at the bottom of the text box
  ) +
    annotate(
    x = 18.87, 
    y = 13, 
    label = "Competence", 
    geom = "text", 
    color = "black",
    fontface="bold",
    size=rel(4),
    vjust = 0,
    angle=-36# Align the label at the bottom of the text box
  ) +
  theme(
     axis.text.y = element_blank(),
    axis.text.x = element_text(size = rel(2)),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),  # Remove default grid lines
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.x = element_blank(), 
    axis.title.y = element_blank(),
    panel.border=element_blank(),
    strip.background = element_rect(color = "black"),
 plot.background = element_rect(fill = "white", color = NA),
 legend.position = "top"
  ) +
  scale_fill_manual(values = plot_colors, labels=c("Hard","Soft"),na.translate = FALSE) +
    scale_color_manual(values = plot_colors) +
  labs(fill="Robot Type") +
  scale_x_discrete(expand = c(0,0),labels = labels_plot2,na.translate = FALSE)+
  guides(color = FALSE, fill=FALSE)

# show plot
spiderplot

ggsave("Figures/spider_plot_2.png", spiderplot, width = 15, height = 9, dpi = 800)
```

## Ridge plot
```{r message=TRUE, warning=FALSE}
dimensions_ridge_wide  <- ggplot(df_long_dimensions, aes(x = value, y = dimension, fill = robot_type)) + 
  geom_density_ridges(aes(color = robot_type), scale = 0.8, alpha = 0.5, rel_min_height = 0.05) +
  stat_pointinterval(position = position_dodge(.8, preserve = "single"), aes(color=robot_type, fill=robot_type), scale=0.6, alpha=0.7) +
  labs(y = "Dimension", x = "Rating") +  
  scale_fill_manual(values = c("#577590","#809BB3"), labels=c("Hard","Soft")) + 
  scale_color_manual(values = c("#577590","#809BB3")) +  
  scale_y_discrete(
    labels = labels_plot, guide = guide_axis(angle = 45)) + 
  scale_x_continuous(breaks=c(0,20,40,60,80,100), limits = c(0,100)) +
  guides(fill = FALSE, color = FALSE)  + coord_flip(clip = "off")

ggsave("Figures/dimensions_ridge_wide_suppl.png", width = 10, height = 3, dpi = 800)
```

## spider plots by robot
```{r}

```

